In [10]:
import pandas as pd
import os

# new cell (index 0)

# set the folder name (replace with the actual folder name under testset)
filename = "curacao_1911_0002"

# build path and load
filepath = f"results/05_transient_transcription_output/knmi/data/00_knmi_images/testset/{filename}.jpg/Top_Excel_with_OCR_Results.xlsx"

ocr_results_df = pd.read_excel(filepath, engine="openpyxl")

# quick inspection
print(f"Loaded: {filepath}")
print("Shape:", ocr_results_df.shape)
ocr_results_df.head()

# convert all cells to strings
ocr_results_df = ocr_results_df.astype(str)
# remove all points and spaces from OCR results for easier comparison
ocr_results_df = ocr_results_df.replace({r'\.': '', r'\s+': ''}, regex=True)
ocr_results_df.head()

Loaded: results/05_transient_transcription_output/knmi/data/00_knmi_images/testset/curacao_1911_0002.jpg/Top_Excel_with_OCR_Results.xlsx
Shape: (36, 24)

,111,111.1,1101,121,01 011,111.2,111.3,112,111.4,011,...,200 011,223,01 0,0101,2001,211,00,3676,3275,6
0,1645,1638,163,2680,2288,1068,2600,2100,21910,580,...,118,18,188,18,110001,1000,00,280,00,81
1,165,1864,1638,2680,138,18,2900,21680,11016,285,...,18,182,11,0,05,250,10,10,01,0
2,1645,169,1636,2600,1569,262,2960,2100,180,119,...,15,178,6186,01,10,3261260,10,00,011,0
3,1645,1681,7335,2600,1168,215,1160,2600,80,11,...,59,51,6125,201,15,361250,10,10,01,01
4,1640,12262,260,800,106,236,2000,nan,100,11,...,182,70,1,01,126,61250,10,nan,00,06

In [11]:
# load ground truth data
ground_truth_filepath = f"/home/teun/knmi/data-rescue-internship-teun/data/ground_truth/{filename}.csv"
ground_truth_df = pd.read_csv(ground_truth_filepath)
ground_truth_df = ground_truth_df.astype(str)
ground_truth_df = ground_truth_df.replace({r'\.': '', r'\s+': ''}, regex=True)
ground_truth_df.head()

,aD,bL_aO,bL_bM,bL_cA,cT_aMe_aO_aD,cT_aMe_aO_bN,cT_aMe_bM_aD,cT_aMe_bM_bN,cT_aMe_cA_aD,cT_aMe_cA_bN,...,fW_aO_bK,fW_bM_aR,fW_bM_bK,fW_cA_aR,fW_cA_bK,gB_aO,gB_bM,gB_cA,gB_dS,hN_aO
0,1,7645,7638,7630,268,234,288,260,270,242,...,30,OZO,40,OZO,30,60,50,60,nan,00
1,2,7650,7640,7634,268,234,278,242,268,230,...,30,O,30,O,30,30,40,50,nan,05
2,3,7645,7640,7636,260,224,284,246,270,242,...,40,O,30,ONO,30,80,40,60,nan,28
3,4,7645,7641,7635,260,220,272,232,260,218,...,40,O,30,ONO,30,50,50,50,nan,113
4,5,7640,7635,7630,260,218,240,208,236,200,...,20,NO,30,ONO,20,40,80,60,nan,08